name: deb package

# Only run this workflow when the push is an annotated tag starting v
on:
  push:
    tags:
      - 'v*'

jobs:
  # This is used to identify the output in other jobs
  Create_Package:
    name: Create deb package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: "REPO"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build amd64
      run: |
        cd REPO
        go build -v -o amd64/usr/bin/time_warden ./...

    - name: Build arm64
      run: |
        cd REPO
        GOOS=linux GOARCH=arm go build -v -o arm64/usr/bin/time_warden ./...

    - name: Build package AMD
      run: |
        mkdir -p PKG_SOURCE_AMD
        cp -Rf REPO/amd64/usr REPO/etc REPO/DEBIAN PKG_SOURCE_AMD
        dpkg-deb --build PKG_SOURCE_AMD time_warden_amd_${{  github.ref_name }}.deb

    - name: Build package ARM
      run: |
        mkdir -p PKG_SOURCE_ARM
        cp -Rf REPO/arm64/usr REPO/etc REPO/DEBIAN PKG_SOURCE_ARM
        dpkg-deb --build PKG_SOURCE_ARM time_warden_arm_${{  github.ref_name }}.deb

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload AMD package
      id: upload-release-asset-amd
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./time_warden_amd_${{  github.ref_name }}.deb
        asset_name: time_warden_amd_${{  github.ref_name }}.deb
        asset_content_type: application/octet-stream

    - name: Upload ARM package
      id: upload-release-asset-arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./time_warden_arm_${{  github.ref_name }}.deb
        asset_name: time_warden_arm_${{  github.ref_name }}.deb
        asset_content_type: application/octet-stream
